// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {backend} from '../models';
import {context} from '../models';

export function AddAndStart(arg1:string,arg2:time.Duration,arg3:backend.JobRunnerFunc,arg4:Array<any>):Promise<void>;

export function GetExecutions():Promise<Array<backend.JobExecution>>;

export function Jobs():Promise<Array<backend.JobState>>;

export function LoadSettings():Promise<string>;

export function Pause(arg1:string):Promise<void>;

export function Resume(arg1:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SetEventEmissions(arg1:boolean):Promise<void>;

export function SetInterval(arg1:string,arg2:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAndRemove(arg1:string):Promise<void>;

export function SyncJobsWithSettings():Promise<void>;

export function SyncJobsWithSettingsPublic():Promise<void>;

export function Trigger(arg1:string):Promise<void>;
