// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAndStart(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['Manager']['AddAndStart'](arg1, arg2, arg3, arg4);
}

export function AddAndStartWithLastRun(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['Manager']['AddAndStartWithLastRun'](arg1, arg2, arg3, arg4, arg5);
}

export function GetExecutions() {
  return window['go']['backend']['Manager']['GetExecutions']();
}

export function Jobs() {
  return window['go']['backend']['Manager']['Jobs']();
}

export function LoadSettings() {
  return window['go']['backend']['Manager']['LoadSettings']();
}

export function Pause(arg1) {
  return window['go']['backend']['Manager']['Pause'](arg1);
}

export function Resume(arg1) {
  return window['go']['backend']['Manager']['Resume'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['Manager']['SaveSettings'](arg1);
}

export function SetEventEmissions(arg1) {
  return window['go']['backend']['Manager']['SetEventEmissions'](arg1);
}

export function SetInterval(arg1, arg2) {
  return window['go']['backend']['Manager']['SetInterval'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['backend']['Manager']['Startup'](arg1);
}

export function StopAndRemove(arg1) {
  return window['go']['backend']['Manager']['StopAndRemove'](arg1);
}

export function SyncJobsWithSettings() {
  return window['go']['backend']['Manager']['SyncJobsWithSettings']();
}

export function SyncJobsWithSettingsPublic() {
  return window['go']['backend']['Manager']['SyncJobsWithSettingsPublic']();
}

export function Trigger(arg1) {
  return window['go']['backend']['Manager']['Trigger'](arg1);
}
